name: Update apps.json weekly (via Worker)

on:
  schedule:
    - cron: "0 0 * * 0"  # 每周日执行
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install beautifulsoup4 requests

      - name: Run Scraper
        run: python scrape_apps_worker.py

      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add apps.json
          git commit -m "Update apps.json from Worker" || echo "No changes"
          git push
